### PR TITLE
Add baseurl support

### PR DESCRIPTION
**Pull request by muradsater**

### CODE REVIEW

**Comment by cognite-cicd** [comment]
#### Checkmarx scan completed with the following findings
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by torbjornopheim** [comment]
Seems like there has been a change in poetry notation since last push, effectively deprecating the current syntax. This blocks Jenkins from building. I will try changing allows-prereleases to allow-prereleases to see if that works:

https://github.com/cognitedata/cognite-replicator/blob/master/pyproject.toml#L32

**Comment by torbjornopheim** [comment]
$ poetry config settings.virtualenvs.create false

[ValueError]
Setting settings.virtualenvs.create does not exist

Couldn't find a quick fix for this

**Comment by gaetan-h** [comment]
Maybe this helps? 
https://github.com/python-poetry/poetry/pull/1272

The settings. prefix is no longer necessary
This one is a breaking change. The settings are now stored differently and no longer needs to be prefixed by settings.. If you have already configured settings you will need to configure them again.

**Pull request merged**
