### PR TITLE
timeseries_exclude_pattern now has effect on datapoint replication as…

### PR DESCRIPTION
**Pull request by torbjornopheim**
Filter now should affect datapoints as well.
Datapoints also raises ValueError when filter and time series are specified. Wanted to create own type for error, but didn't find quick fix.

### CODE REVIEW

**Comment by cognite-cicd** [comment]
#### Checkmarx scan completed with the following findings
|Lines|Severity|Category|File|Link|
---|---|---|---|---

**Comment by tristan-cognite** [comment]
Version number should be update in pyproject.toml as well.

What is the use case where we need regex filtering on datapoints? If we apply the filtering to timeseries replication, datapoints replication will only happen on these timeseries. Or if the time series are already replicated and we only want to replicate datapoints on specific timeseries, then we can pass a list of specific external ids. 

I think it might be better not to raise ValueError, but I'm not sure. On one hand, presumably it doesn't make any sense to have both. But on the other hand, if you are using a generated list of ids, you probably don't want the replication to completely fail just because you also have a filter rule. Maybe we could log excluded time series when we are doing replication on specific timeseries?

**Comment by magneei** [comment]
The use case for Aker Solution is the following:

   - They have Prod and Dev environments.
   - In both environments they write Synthetic time series based on "Real"
   timeseries.
   - So the time series which are prefixed SYN will exist on both tenants
   should not be replicated

It was my suggestion to generate an error if both filter and tag list were
given as parameters, mainly because it is non-obvious for the user how
these two would interact, and it is better to generate an error, than to
have unpredictable behaviour, especially since I don't see a use case where
you would use both at the same time. But happy to have this challenged if
any of my assumptions are wrong or some other behaviour is better.

man. 2. des. 2019 kl. 14:34 skrev Tristan Monger <notifications@github.com>:

**Comment by tristan-cognite** [comment]
I think I understand now. We want the time series to exist in Dev, but to be independent from the Prod time series. This is a good solution. 

For the ValueError discussion, I think raising the exception is probably the best in terms of usefulness vs. speed of development. I was wondering whether we will face the case where we want to replicate a list of external ids (probably generated from 3rd party software or some sql query) but only those that meet the regex criteria. I guess that in this case we might say that the SQL or other source should be responsible for applying the filter.

**Comment by torbjornopheim** [comment]
Yeah, me and Magne had a discussion about it and it sounds like it's a fair assumption to make. And it's better to fail than to have unexpected behavior. 👍

**Pull request merged**
